package com.castis.pvs.entity;


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContentProvider generated by hbm2java
 */
@Entity
@Table(name = "content_provider")
public class ContentProvider implements java.io.Serializable {

	private Long idx;
	private String providerId;
	private String cpName;
	private Short cpType;
	private String cpDescription;
	private String idDomain;
	private String ftpPath;
	private Date creationTime;
	private Date lastUpdateTime;
	private Set<User> users = new HashSet<User>(0);

	public ContentProvider() {
	}

	public ContentProvider(String providerId, String cpName, Short cpType, String idDomain, String ftpPath) {
		this.providerId = providerId;
		this.cpName = cpName;
		this.cpType = cpType;
		this.idDomain = idDomain;
		this.ftpPath = ftpPath;
	}

	

	@Column(name = "idx", nullable = false)
	public Long getIdx() {
		return idx;
	}

	public void setIdx(Long idx) {
		this.idx = idx;
	}

	@Id
	@Column(name = "provider_id", unique = true, nullable = false, length = 50)
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	@Column(name = "cp_name", nullable = false, length = 64)
	public String getCpName() {
		return this.cpName;
	}

	public void setCpName(String cpName) {
		this.cpName = cpName;
	}

	@Column(name = "cp_type", nullable = false, length = 6)
	public Short getCpType() {
		return cpType;
	}

	public void setCpType(Short cpType) {
		this.cpType = cpType;
	}

	@Column(name = "cp_description", length = 1024)
	public String getCpDescription() {
		return this.cpDescription;
	}

	public void setCpDescription(String cpDescription) {
		this.cpDescription = cpDescription;
	}

	@Column(name = "id_domain", nullable = false, length = 256)
	public String getIdDomain() {
		return this.idDomain;
	}

	public void setIdDomain(String idDomain) {
		this.idDomain = idDomain;
	}

	@Column(name = "ftp_path", nullable = false, length = 512)
	public String getFtpPath() {
		return this.ftpPath;
	}

	public void setFtpPath(String ftpPath) {
		this.ftpPath = ftpPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_time", length = 19)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentProvider")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
