package com.castis.pvs.entity;


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserRoleMap generated by hbm2java
 */
@Entity
@Table(name = "user_role_map")
public class UserRoleMap implements java.io.Serializable {

	private Integer id;
	private Role role;
	private User user;

	public UserRoleMap() {
	}

	public UserRoleMap(Role role, User user) {
		this.role = role;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
